# Generated by Django 4.1.3 on 2022-11-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviecategory',
            options={'verbose_name': 'movie category', 'verbose_name_plural': 'movie categories'},
        ),
        migrations.AlterModelOptions(
            name='moviefile',
            options={'verbose_name': 'movie file', 'verbose_name_plural': 'movie files'},
        ),
    ]
